//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WineApiUnitTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WineApiUnitTests.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;Status&quot; : {
        ///		&quot;Messages&quot; : [],
        ///		&quot;ReturnCode&quot; : 0
        ///	},
        ///			&quot;Id&quot; : 4,
        ///			&quot;Name&quot; : &quot;Wine Type&quot;,
        ///			&quot;Refinements&quot; : [{
        ///					&quot;Id&quot; : 124,
        ///					&quot;Name&quot; : &quot;Red Wine&quot;,
        ///					&quot;Url&quot; : &quot;&quot;
        ///				}, {
        ///					&quot;Id&quot; : 125,
        ///					&quot;Name&quot; : &quot;White Wine&quot;,
        ///					&quot;Url&quot; : &quot;&quot;
        ///				}, {
        ///					&quot;Id&quot; : 126,
        ///					&quot;Name&quot; : &quot;Rosé Wine&quot;,
        ///					&quot;Url&quot; : &quot;&quot;
        ///				}, {
        ///					&quot;Id&quot; : 123,
        ///					&quot;Name&quot; : &quot;Champagne &amp; Sparkling&quot;,
        ///					&quot;Url&quot; : &quot;&quot;
        ///				}, {
        ///					&quot;Id&quot; : 134,
        ///					&quot;Name&quot; : &quot;Saké&quot;,
        ///					&quot;Url&quot; : &quot;&quot;
        ///				}, {
        ///					&quot;Id&quot; : 12 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BadJson {
            get {
                return ResourceManager.GetString("BadJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;Status&quot; : {
        ///		&quot;Messages&quot; : [],
        ///		&quot;ReturnCode&quot; : 0
        ///	},
        ///	&quot;Products&quot; : {
        ///		&quot;List&quot; : [{
        ///				&quot;Id&quot; : 108074,
        ///				&quot;Name&quot; : &quot;Duckhorn Napa Merlot 2008&quot;,
        ///				&quot;Url&quot; : &quot;http:\/\/www.wine.com\/V6\/Duckhorn-Napa-Merlot-2008\/wine\/108074\/detail.aspx&quot;,
        ///				&quot;Appellation&quot; : {
        ///					&quot;Id&quot; : 2398,
        ///					&quot;Name&quot; : &quot;Napa Valley&quot;,
        ///					&quot;Url&quot; : &quot;http:\/\/www.wine.com\/v6\/Napa-Valley\/wine\/list.aspx?N=7155+101+2398&quot;,
        ///					&quot;Region&quot; : {
        ///						&quot;Id&quot; : 101,
        ///						&quot;Name&quot; : &quot;California&quot;,
        ///						&quot;Url&quot; : &quot;http:\/\/www.w [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MerlotNapaValleyProducts {
            get {
                return ResourceManager.GetString("MerlotNapaValleyProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;Status&quot; : {
        ///		&quot;Messages&quot; : [],
        ///		&quot;ReturnCode&quot; : 0
        ///	},
        ///	&quot;Blog&quot; : [],
        ///	&quot;Books&quot; : [{
        ///			&quot;Id&quot; : &quot;5&quot;,
        ///			&quot;Title&quot; : &quot;Varietal&quot;,
        ///			&quot;Articles&quot; : [{
        ///					&quot;Id&quot; : &quot;138&quot;,
        ///					&quot;Title&quot; : &quot;Merlot&quot;,
        ///					&quot;Abstract&quot; : &quot; Merlot\u000d(mehr-LOW) \u000d\u000dRelated Links:\u000d Shop our most popular Merlots\u000d Shop our highest rated Merlots \u000d No second fiddle\u000d Poor Merlot, Miles gave it quite a reputation in Sideways. Luckily, Merlot did...&quot;,
        ///					&quot;Content&quot; : &quot; Merlot\u000d(mehr-LOW) \u000d\u000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MerlotReferences {
            get {
                return ResourceManager.GetString("MerlotReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;Status&quot; : {
        ///		&quot;Messages&quot; : [&quot;Message1&quot;, &quot;Message2&quot;],
        ///		&quot;ReturnCode&quot; : 200
        ///	},
        ///	&quot;Categories&quot; : []
        ///}
        ///.
        /// </summary>
        internal static string StatusWithReturnCode200And2Messages {
            get {
                return ResourceManager.GetString("StatusWithReturnCode200And2Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;Status&quot; : {
        ///		&quot;Messages&quot; : [&quot;Message1&quot;, &quot;Message2&quot;],
        ///		&quot;ReturnCode&quot; : 123
        ///	},
        ///	&quot;Categories&quot; : []
        ///}
        ///.
        /// </summary>
        internal static string StatusWithUnknownReturnCode {
            get {
                return ResourceManager.GetString("StatusWithUnknownReturnCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;Status&quot; : {
        ///		&quot;Messages&quot; : [],
        ///		&quot;ReturnCode&quot; : 0
        ///	},
        ///	&quot;Categories&quot; : [{
        ///			&quot;Id&quot; : 4,
        ///			&quot;Name&quot; : &quot;Wine Type&quot;,
        ///			&quot;Refinements&quot; : [{
        ///					&quot;Id&quot; : 124,
        ///					&quot;Name&quot; : &quot;Red Wine&quot;,
        ///					&quot;Url&quot; : &quot;&quot;
        ///				}, {
        ///					&quot;Id&quot; : 125,
        ///					&quot;Name&quot; : &quot;White Wine&quot;,
        ///					&quot;Url&quot; : &quot;&quot;
        ///				}, {
        ///					&quot;Id&quot; : 126,
        ///					&quot;Name&quot; : &quot;Rosé Wine&quot;,
        ///					&quot;Url&quot; : &quot;&quot;
        ///				}, {
        ///					&quot;Id&quot; : 123,
        ///					&quot;Name&quot; : &quot;Champagne &amp; Sparkling&quot;,
        ///					&quot;Url&quot; : &quot;&quot;
        ///				}, {
        ///					&quot;Id&quot; : 134,
        ///					&quot;Name&quot; : &quot;Saké&quot;,
        ///					&quot;Url&quot; : &quot;&quot;
        ///				 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WineTypes {
            get {
                return ResourceManager.GetString("WineTypes", resourceCulture);
            }
        }
    }
}
